name: Deploy to Pantheon
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LH_PANTHEON_PRIVATE_KEY }}
        known_hosts: ${{ secrets.LH_KNOWN_HOSTS }}

    - name: deployer
      env:
        pantheon_repo: '${{ secrets.LH_PANTHEON_REPO }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        git remote add pantheon $pantheon_repo
        git config --global user.email "matt@almanac.digital"
        git config --global user.name "mattalmanac"
        git add .
        git commit -q -m 'Deploy to Pantheon from Github'
        git push --force pantheon HEAD:refs/heads/$BASE_BRANCH